CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS intermediate;
CREATE SCHEMA IF NOT EXISTS production;


-- JKK importide hoimise tabel
CREATE TABLE IF NOT EXISTS staging.raw_snapshot (
    run_id uuid PRIMARY KEY,
    fetched_at timestamptz NOT NULL,
    source_name text NOT NULL,
    row_count int,
    raw_data jsonb NOT NULL,
    status text NOT NULL,
    message text
);

-- JKK registri puhastatud vahetabel

CREATE TABLE IF NOT EXISTS intermediate.jkk_curr_clean (
    oid bigint GENERATED BY DEFAULT AS IDENTITY,
    
    -- Otse API-st pärinevad väljad
    objekti_nimetus text,
    jkk_kood text,
    jkk_olukord text,
    kaitaja_nimi text,
    kaitaja_kood text,
    aadress text,
    teised_aadressid text,
    x_koordinaat integer,
    y_koordinaat integer,
    tegevus text,
    tegevus_selg text,
    tegevuse_tapsustus text,
    tegevuse_algus date,
    tegevuse_lopp date,
    muudetud text,
    komplekstegevus text,
    komplekstegevus_selg text, 
    jaatmete_kaitlemine text,
    
    -- Järeltöödeldud väljad
    jkk_kood_ext text, -- jkk_kood + kat_id > unikaalne obj sihtsüsteemi jaoks
    nimi text,
    lyhinimi text,
    brand text,
    kat_id integer,
    liigisona text,
    lipikud text,

    -- Geomeetria veerg, täitub x-y põhjal automaatselt
    geom geometry(Point, 3301) GENERATED ALWAYS AS (
        CASE
            WHEN x_koordinaat IS NULL OR y_koordinaat IS NULL THEN NULL
            ELSE ST_SetSRID(
                ST_MakePoint(y_koordinaat, x_koordinaat),
                3301
            )
        END
    ) STORED,
    CONSTRAINT pk_jkk_curr_clean PRIMARY KEY (oid)
);

CREATE INDEX IF NOT EXISTS ix_jkk_curr_clean_geom
ON intermediate.jkk_curr_clean
USING gist (geom);

-- JKK registri täisvaade lõppkasutajale
-- sisaldab nii API-st pärinevaid kui ka spetsialistide/sihtsüsteemi poolt hallatud välju

CREATE TABLE IF NOT EXISTS production.jkk_full (
    oid bigint GENERATED BY DEFAULT AS IDENTITY,
    
    -- Otse API-st pärinevad väljad
    objekti_nimetus text,
    jkk_kood text,
    jkk_olukord text,
    kaitaja_nimi text,
    kaitaja_kood text,
    aadress text,
    teised_aadressid text,
    x_koordinaat integer,
    y_koordinaat integer,
    tegevus text,
    tegevus_selg text,
    tegevuse_tapsustus text,
    tegevuse_algus date,
    tegevuse_lopp date,
    muudetud text,
    komplekstegevus text,
    komplekstegevus_selg text, 
    jaatmete_kaitlemine text,
    
    -- Järeltöödeldud väljad
    jkk_kood_ext text, -- jkk_kood + kat_id > unikaalne obj sihtsüsteemi jaoks
    nimi text,
    lyhinimi text,
    brand text,
    kat_id integer,
    liigisona text,
    lipikud text,
    
    -- sihtsüsteemi/spetsialistide poolt hallatavad väljad
    poi_id integer,
    staatus integer,
    kommentaar text,
    added_date date,
    resolved_date date,
    -- registri geomeetria veerg
    geom geometry(Point, 3301),
    -- sihtsüsteemi/spetsialistide poolt hallatav geomeetria
    geom_mod geometry(Point, 3301),
    CONSTRAINT pk_jkk_full PRIMARY KEY (oid)
);

CREATE INDEX IF NOT EXISTS ix_jkk_full_geom
ON production.jkk_full
USING gist (geom);

CREATE INDEX IF NOT EXISTS ix_jkk_full_geom_mod
ON production.jkk_full
USING gist (geom_mod);

-- registrist eemaldatud objektide kumulatiivne tabel
CREATE TABLE IF NOT EXISTS production.jkk_removed (
    oid bigint GENERATED BY DEFAULT AS IDENTITY,
    
    -- Otse API-st pärinevad väljad
    objekti_nimetus text,
    jkk_kood text,
    jkk_olukord text,
    kaitaja_nimi text,
    kaitaja_kood text,
    aadress text,
    teised_aadressid text,
    x_koordinaat integer,
    y_koordinaat integer,
    tegevus text,
    tegevus_selg text,
    tegevuse_tapsustus text,
    tegevuse_algus date,
    tegevuse_lopp date,
    muudetud text,
    komplekstegevus text,
    komplekstegevus_selg text, 
    jaatmete_kaitlemine text,
    
    -- Järeltöödeldud väljad
    jkk_kood_ext text, -- jkk_kood + kat_id > unikaalne obj sihtsüsteemi jaoks
    nimi text,
    lyhinimi text,
    brand text,
    kat_id integer,
    liigisona text,
    lipikud text,
    
    -- väljad jkk_full tabelist
    poi_id integer,
    staatus integer,
    kommentaar text,
    added_date date,
    resolved_date date,

    -- sihtsüsteemi/spetsialistide poolt hallatavad veerud 
    removed_date date ,
    remove_resolved_date date,
    -- geomeetriad (samad, mis jkk_full tabelis)
    geom geometry(Point, 3301),
    geom_mod geometry(Point, 3301),
    CONSTRAINT pk_jkk_removed PRIMARY KEY (oid)
);

CREATE INDEX IF NOT EXISTS ix_jkk_removed_geom
ON production.jkk_removed
USING gist (geom);

CREATE INDEX IF NOT EXISTS ix_jkk_removed_geom_mod
ON production.jkk_removed
USING gist (geom_mod);

-- Muutuste kumulatiivne tabel

CREATE TABLE IF NOT EXISTS production.jkk_changes (
    oid bigint GENERATED BY DEFAULT AS IDENTITY,
    objekti_nimetus text,
    jkk_kood_ext text,
    -- Nime muutus
    nimi_change_status integer DEFAULT 0,
    nimi_old text,
    nimi_new text,
    -- Haldaja / brandi muutus
    brand_change_status integer DEFAULT 0,
    brand_old text,
    brand_new text,
    -- Liigisõna muutus
    liigisona_change_status integer DEFAULT 0,
    liigisona_old text,
    liigisona_new text,
    -- Lipikute muutus
    lipikud_change_status integer DEFAULT 0,
    lipikud_old text,
    lipikud_new text,
    -- Geomeetria muutus
    geom_change_status integer DEFAULT 0,
    geom_change geometry(LineString, 3301),
    -- Käsitlemise väljad
    kommentaar text,
    change_date date,
    resolved_date date,
    geom geometry(Point, 3301),
    CONSTRAINT pk_jkk_changes PRIMARY KEY (oid)
);

CREATE INDEX IF NOT EXISTS ix_jkk_changes_geom
ON production.jkk_changes
USING gist (geom);

CREATE INDEX IF NOT EXISTS ix_jkk_changes_geom_change
ON production.jkk_changes
USING gist (geom_change);